version: "3"

services:

  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=0 #root 权限
      - PGID=0
      - TZ=Asia/Shanghai
      - PASSWORD=root #optional
      - SUDO_PASSWORD=root #optional
      # - PROXY_DOMAIN=localhost/code-server/ #optional
      - DEFAULT_WORKSPACE=/root/projects/docker-deploy-configuration #optional
    volumes:
      - /root:/root
      - /mnt/ssd/dockerd/code-server/config:/config
      - ./config.yaml:/config/.config/code-server/config.yaml
    ports:
      - 8443:8443
