
version: "3"
services:
  sonarqube:
    image: sonarqube:community
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /mnt/ubuntu.old/root/dockerd/sonarqube/data:/opt/sonarqube/data
      - /mnt/ubuntu.old/root/dockerd/sonarqube/extensions:/opt/sonarqube/extensions
      - /mnt/ubuntu.old/root/dockerd/sonarqube/logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /mnt/ubuntu.old/root/dockerd/sonarqube/postgresql:/var/lib/postgresql
      - /mnt/ubuntu.old/root/dockerd/sonarqube/postgresql/data:/var/lib/postgresql/data
