version: '3.3'

services:
    express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://172.17.0.1:27017
