version: "3"

networks:
  gitea-postgres:
    external: false

services:

  # ----------------------------------------------
  server:
    image: gitea/gitea:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    networks:
      - gitea-postgres
    volumes:
      - ./conf.ini:/data/gitea/conf/app.ini
      - /mnt/ssd/dockerd/gitea/data:/data
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "13000:3000"
      - "10022:22"
    depends_on:
      - postgres
      - redis

  # ----------------------------------------------
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea-postgres
    volumes:
      - /mnt/ssd/dockerd/gitea/postgres:/var/lib/postgresql/data
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - 15432:5432

  # ----------------------------------------------
  redis:
    image: redis:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "16379:6379"
    volumes:
      - /mnt/ssd/dockerd/gitea/redis:/data
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea-postgres
