version: "3"

networks:
  gitea-postgres:
    external: false

services:
  server:
    image: gitea/gitea:latest
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    networks:
      - gitea-postgres
    volumes:
      - /mnt/ssd/dockerd/gitea/data:/data
      - $PWD/conf.ini:/data/gitea/conf/app.ini
      - $PWD/.gitconfig:/data/git/.gitconfig
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "13001:3000"
      - "10023:22"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea-postgres
    volumes:
      - /mnt/ssd/dockerd/gitea/postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
