version: '3'

networks:
  public-servers:
    external: true

services:

  redis:
    image: redis:latest
    restart: always
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - /mnt/ssd/dockerd/public/redis:/data
    networks:
      - public-servers

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /mnt/ssd/dockerd/public/mongo:/data
    networks:
      - public-servers

  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ssd/dockerd/public/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - public-servers
