version: '3'

services:

  # ----------------------------------------------
  server:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /mnt/ssd/dockerd/nextcloud/nextcloud:/var/www/html
      - /mnt/linux.backup/dockerd/nextcloud/data:/var/www/html/data
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=root
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud

  # ----------------------------------------------
  mysql:
    image: mariadb:latest
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/ssd/dockerd/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    ports:
      - 13306:3306

  # ----------------------------------------------
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 18081:8080
    environment:
      - TZ=Asia/Shanghai
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_DEFAULT_DB_HOST=mysql
      - ADMINER_DEFAULT_DB_NAME=nextcloud
      - ADMINER_DESIGN=nette
      - PHP_CLI_MEMORY_LIMIT=1024m
    depends_on:
      - mysql
