
version: '3'

services:
  rabbit:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - /mnt/ssd/dockerd/rabbitmq:/var/lib/rabbitmq
