version: '3.7'

services:
  
  consul-server:
    image: consul
    container_name: consul-server
    restart: always
    volumes:
     - ./config.server.json:/consul/config/server.json:ro
     - /mnt/ssd/dockerd/consul/server:/consul/data
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: consul
    container_name: consul-client
    restart: always
    volumes:
     - ./config.client.json:/consul/config/client.json:ro
     - /mnt/ssd/dockerd/consul/client:/consul/data
    networks:
      - consul
    command: "agent"

networks:
  consul:
    driver: bridge
