version: '3'

networks:
  public-servers:
    external: true

services:

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - /mnt/ssd/dockerd/redis:/data
    networks:
      - public-servers
