version: '3.1'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql-main
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ubuntu.old/root/dockerd/mysql:/var/lib/mysql
      # - $PWD/conf.ini:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
