version: '3.9'

services:
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - /mnt/ssd/dockerd/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster-main