version: "3"

services:

  # -----------------------------
  main:
    image: syncthing/syncthing
    hostname: syncthing-main
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/ssd/dockerd/syncthing/main:/var/syncthing
      - /mnt/linux.backup:/backup
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts

  # -----------------------------
  ubuntu:
    image: syncthing/syncthing
    hostname: syncthing-ubuntu
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/ssd/dockerd/syncthing/ubuntu:/var/syncthing
      - /:/backup
    ports:
      - 8385:8384 # Web UI
      - 22001:22000/tcp # TCP file transfers
      - 22001:22000/udp # QUIC file transfers
      - 21028:21027/udp # Receive local discovery broadcasts
