version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /mnt/ssd/dockerd/postgre:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
