version: '3'
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis-main
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/etc/redis/redis.conf
      - /mnt/ubuntu.old/root/dockerd/redis:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true
